### ISSUE TITLE
Please publish update for CLion 2024 build 243

### ISSUE THREAD

**Issue by rsmz** [zerolfx/rr#1]
Would it also be possible to explain in your README how to prepare the plugin for any CLion build when cloned by any developer? Thank you.

**Comment by zerolfx** [comment]
I will update it.

Thanks for letting me know it might be useful to others.

To build it, clone the project and adjust some configurations (similar to https://github.com/zerolfx/rr/commit/2e1a16b18aaf4602933b808f0d2aeed0eaa87665). The GitHub Action will handle the rest. For more information on building and configuration, please visit https://github.com/JetBrains/intellij-platform-plugin-template.

**Comment by zerolfx** [comment]
There are some breaking changes from JetBrains, and I failed to fix the dependency-related problem (see Actions for details).

Can you help on it? Or I will seek help from the community next week.

**Comment by zerolfx** [comment]
The build was fixed. I uploaded it to JetBrains Marketplace and it will be available after ~2 days.

You can also use the plugin built by GitHub Action (download and install it from local disk).
